"""Shell tab-completion, generated from the CLI itself.

The scripts are built by introspecting every command's real argparse parser at
generation time, so completion can't drift from the actual flags. Install:

    zsh:   mkdir -p ~/.zfunc && pdfblah completions zsh > ~/.zfunc/_pdfblah
           # ensure ~/.zfunc is in fpath before compinit
    bash:  echo 'eval "$(pdfblah completions bash)"' >> ~/.bashrc
"""
import io
import re
from contextlib import redirect_stderr, redirect_stdout


def _command_flags():
    """{command: [--flags]} pulled from each parser's own --help text."""
    from .cli import HANDLERS, main
    from .cli_tools import TOOL_HANDLERS

    cmds = sorted((set(HANDLERS) | set(TOOL_HANDLERS)) - {"gui"})
    out = {}
    for c in cmds:
        buf = io.StringIO()
        try:
            with redirect_stdout(buf), redirect_stderr(buf):
                main([c, "--help"])
        except SystemExit:
            pass
        flags = sorted(set(re.findall(r"--[\w-]+", buf.getvalue())) - {"--help"})
        out[c] = flags
    return out


def script(shell):
    from .surface import COMMANDS

    flags = _command_flags()
    if shell == "zsh":
        return _zsh(flags, COMMANDS)
    return _bash(flags, COMMANDS)


def _zsh(flags, commands):
    descs = []
    for c in sorted(flags):
        summary = commands.get(c, {}).get("summary", "").replace("'", "'\\''")
        descs.append(f"    '{c}:{summary}'")
    cases = []
    for c, fl in sorted(flags.items()):
        cases.append(f'    {c}) _arguments {" ".join(chr(39) + f + chr(39) for f in fl)} '
                     f"'*:file:_files' ;;")
    return f"""#compdef pdfblah
# generated by `pdfblah completions zsh`
_pdfblah() {{
  local -a _cmds
  _cmds=(
{chr(10).join(descs)}
  )
  if (( CURRENT == 2 )); then
    _describe -t commands 'pdfblah command' _cmds
    _files -g '*.pdf'
    return
  fi
  case $words[2] in
{chr(10).join(cases)}
    *) _files ;;
  esac
}}
_pdfblah "$@"
"""


def _bash(flags, commands):
    cases = []
    for c, fl in sorted(flags.items()):
        cases.append(f'    {c}) opts="{" ".join(fl)}" ;;')
    return f"""# generated by `pdfblah completions bash`
_pdfblah() {{
  local cur cmd opts
  cur="${{COMP_WORDS[COMP_CWORD]}}"
  cmd="${{COMP_WORDS[1]}}"
  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "{" ".join(sorted(flags))}" -- "$cur") )
    return
  fi
  opts=""
  case "$cmd" in
{chr(10).join(cases)}
  esac
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
  else
    COMPREPLY=( $(compgen -f -- "$cur") )
  fi
}}
complete -F _pdfblah pdfblah
"""
